[package]
name = "tauri-specta"
description = "Completely typesafe Tauri commands"
version = "0.0.2"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/README.md", "/LICENCE"]
repository = "https://github.com/oscartbeaumont/tauri-specta"
documentation = "https://docs.rs/tauri-specta/latest/tauri-specta"
keywords = ["async", "specta", "rspc", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

[dependencies]
specta = { git = "https://github.com/oscartbeaumont/rspc.git", rev = "ab4ec20b944fab7f15d5e3ad17b188ddd37ede0d", features = ["command", "tauri", "openapi"] }

openapiv3 = "1.0.1"
paste = "1.0.9"
serde = "1.0.147"
serde_json = "1.0.87"
tauri = "1.1.1"
thiserror = "1.0.37"

[workspace]
members = [
    "example/src-tauri"
]
