[package]
name = "tauri-specta"
description = "Completely typesafe Tauri commands"
version = "2.0.0-rc.4"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/README.md", "/LICENCE"]
repository = "https://github.com/oscartbeaumont/tauri-specta"
documentation = "https://docs.rs/tauri-specta/latest/tauri-specta"
keywords = ["async", "specta", "rspc", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
javascript = ["specta/typescript", "specta/js_doc"]
typescript = ["specta/typescript", "specta/js_doc"]

[dependencies]
# Public
specta = { version = "=2.0.0-rc.10", features = ["function"] }
tauri-specta-macros = { version = "=2.0.0-rc.4", path = "./macros" }
serde = "1"
serde_json = "1"
thiserror = "1"
tauri = { version = "=2.0.0-beta.16", features = ["specta"] }

# Private
heck = "0.5.0"
indoc = "2.0.5"

[dev-dependencies]
doc-comment = "0.3.3"

[workspace]
members = [
    "examples/app/src-tauri",
    "examples/custom-plugin/app/src-tauri",
    "examples/custom-plugin/plugin",
    "macros",
]

[patch.crates-io]
tauri = { git = "https://github.com/tauri-apps/tauri", rev = "3f0805488506e013e15cfb3cc1cfc8c2c5f84bd2" }
