[package]
name = "tauri-specta"
description = "Completely typesafe Tauri commands"
version = "2.0.0-rc.11"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/README.md", "/LICENCE"]
repository = "https://github.com/oscartbeaumont/tauri-specta"
documentation = "https://docs.rs/tauri-specta/latest/tauri-specta"
keywords = ["async", "specta", "rspc", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
javascript = ["dep:specta-typescript"]
typescript = ["dep:specta-typescript"]

# TODO: https://github.com/tauri-apps/tauri/pull/10435
UNSTABLE_channels = []

[dependencies]
# Public
specta = { workspace = true, features = ["function"] }
specta-typescript = { workspace = true, optional = true }
specta-util = { workspace = true }
tauri-specta-macros = { version = "=2.0.0-rc.5", path = "./macros" }
serde = "1"
serde_json = "1"
thiserror = "1"
tauri = { workspace = true, default-features = false, features = ["specta"] }

# Private
heck = "0.5.0"
indoc = "2.0.5"

[workspace]
members = [
  "examples/app/src-tauri",
  "examples/custom-plugin/app/src-tauri",
  "examples/custom-plugin/plugin",
  "macros",
]

[workspace.dependencies]
tauri = { version = "=2.0.0-beta.25" }
specta = { version = "=2.0.0-rc.16" }
specta-util = { version = "0.0.3" }
specta-typescript = { version = "0.0.3" }

[patch.crates-io]
# tauri = { git = "https://github.com/oscartbeaumont/tauri.git", branch = "fix-channel-specta-remote-impl" }
# tauri-build = { git = "https://github.com/oscartbeaumont/tauri.git", branch = "fix-channel-specta-remote-impl" }

specta = { path = "../specta/specta" }
specta-util = { path = "../specta/specta-util" }
specta-typescript = { path = "../specta/specta-typescript" }
