[package]
name = "tauri-specta"
version = "0.1.0"
edition = "2021"

[dependencies]
openapiv3 = "1.0.1"
serde = "1.0.147"
serde_json = "1.0.87"
specta = { git = "https://github.com/oscartbeaumont/rspc", features = ["openapi"] } # TODO: We need this for alpha OpenAPI support
tauri = "1.1.1"
tauri-specta-macros = { path = "./macros" }
thiserror = "1.0.37"

[workspace]
members = [
    "macros",
    "example/src-tauri"
]
