[package]
name = "example"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"
publish = false

[build-dependencies]
tauri-build = { version = "1.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2.0", features = ["api-all"] }
tauri-specta = { path = "../../" }
specta = { git = "https://github.com/oscartbeaumont/rspc.git", rev = "ab4ec20b944fab7f15d5e3ad17b188ddd37ede0d", features = ["command", "tauri", "openapi"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
